name: x86_64 Ubuntu ? build

on:
  push:
  pull_request:

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')&&!contains(github.event.commits[0].message, '[ci skip]')&&!contains(github.event.commits[0].message, '[skip build]')"
    runs-on: ubuntu-latest
    steps:
        - run: "sudo apt install libcurl4-openssl-dev"
          name: "fucking soultion"
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"
        # fixme: fork bomb
        - name: make
          run: make -j
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            path: jvav
            # platfrom-name-version-builder
            # todo: append _github_actions_hosted_runner to builder field where possible
            name: x86_64-pc-linux-jvav-9git-azure_vm_ubuntu
  build-mingw-x86_64:
    if: "!contains(github.event.commits[0].message, '[skip ci]')&&!contains(github.event.commits[0].message, '[ci skip]')&&!contains(github.event.commits[0].message, '[skip mingw build]')"
    runs-on: windows-latest
    steps:
        - shell: cmd
          run: |
            cd /d C:
            mkdir MinGW
            rem whatever
            curl -O https://lwys-file-bucket-uax4yp6.netlify.app/mingw-17.1-nuwen-cleanup.7z
            7z x mingw-17.1-nuwen-cleanup.7z -oC:\MinGW -y -aoa -bb3 -slt
            del /y mingw-17.1-nuwen-cleanup.7z
            cd MinGW
            set_distro_paths
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"
        # fixme: fork bomb
        - name: install curl
          shell: cmd
          run: |
            curl -o curl-for-win.zip https://curl.haxx.se/windows/dl-7.70.0/curl-7.70.0-win64-mingw.zip
            7z x curl-for-win.zip -y -aoa -bb3 -slt
            xcopy curl-7.70.0-win64-mingw\*.* c:\MinGW\x86_64-w64-mingw32 /y /s /e
            xcopy curl-7.70.0-win64-mingw\*.* c:\MinGW /y /s /e
        - name: make
          shell: cmd
          run: make -j GHA_RUNNER_WINDOWS=y
        - name: "gen bin"
          run: |
            mkdir bin
            cd bin
            copy ..\jvav.exe .
            # copy c:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin\libcurl-x64.dll .
            # copy c:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin\curl-ca-bundle.crt .
            # copy ..\.github\workflows_meta\*.dll .
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            path: bin
            # platfrom-name-version-builder
            # todo: append _github_actions_hosted_runner to builder field where possible
            name: x86_64-pc-winnt-jvav-9git-azure_vm_winnt
  build-nonetwork:
    if: "!contains(github.event.commits[0].message, '[skip ci]')&&!contains(github.event.commits[0].message, '[ci skip]')&&!contains(github.event.commits[0].message, '[skip networkless build]')"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"
        # fixme: fork bomb
        - name: make
          run: make -j NO_NETWORKING=y
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            path: jvav
            # platfrom-name-version-builder
            # todo: append _github_actions_hosted_runner to builder field where possible
            name: x86_64-pc-linux-jvav-9git-nonet-azure_vm_ubuntu
  build-mingw-x86_64-nonetwork:
    if: "!contains(github.event.commits[0].message, '[skip ci]')&&!contains(github.event.commits[0].message, '[ci skip]')&&!contains(github.event.commits[0].message, '[skip networkless mingw build]')"
    runs-on: windows-latest
    steps:
        - shell: cmd
          run: |
            cd /d C:
            mkdir MinGW
            rem whatever
            curl -O https://lwys-file-bucket-uax4yp6.netlify.app/mingw-17.1-nuwen-cleanup.7z
            7z x mingw-17.1-nuwen-cleanup.7z -oC:\MinGW -y -aoa -bb3 -slt
            del /y mingw-17.1-nuwen-cleanup.7z
            cd MinGW
            set_distro_paths
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"
        # fixme: fork bomb
        - name: make
          run: make -j GHA_RUNNER_WINDOWS=y NO_NETWORKING=y
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            path: jvav.exe
            # platfrom-name-version-builder
            # todo: append _github_actions_hosted_runner to builder field where possible
            name: x86_64-pc-winnt-jvav-9git-nonet-azure_vm_winnt