name: x86_64 Ubuntu ? build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - run: "sudo apt install libcurl4-openssl-dev"
          name: "fucking soultion"
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"
        # fixme: fork bomb
        - name: make
          run: make -j
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            path: jvav
            # platfrom-name-version-builder
            # todo: append _github_actions_hosted_runner to builder field where possible
            name: x86_64-pc-linux-jvav-9git-azure_vm_ubuntu
  build-mingw-x86_64:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"
        # fixme: fork bomb
        - name: make
          run: |
            set GHA_RUNNER_WINDOWS=y
            make -j
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            path: jvav.exe
            # platfrom-name-version-builder
            # todo: append _github_actions_hosted_runner to builder field where possible
            name: x86_64-pc-winnt-jvav-9git-azure_vm_winnt