name: x86_64 Ubuntu ? build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - run: "sudo apt install libcurl4-openssl-dev"
          name: "fucking soultion"
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"
        # fixme: fork bomb
        - name: make
          run: make -j
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            path: jvav
            # platfrom-name-version-builder
            # todo: append _github_actions_hosted_runner to builder field where possible
            name: x86_64-pc-linux-jvav-9git-azure_vm_ubuntu
  build-mingw-x86_64:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"
        # fixme: fork bomb
        - name: install curl
          shell: cmd
          run: |
            curl -o curl-for-win.zip https://curl.haxx.se/windows/dl-7.70.0/curl-7.70.0-win64-mingw.zip
            7z x curl-for-win.zip -y -aoa -bb3 -slt
            xcopy curl-7.70.0-win64-mingw\*.* c:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32 /y /s /e
            xcopy curl-7.70.0-win64-mingw\*.* c:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64 /y /s /e
        - name: make
          shell: cmd
          run: make -j GHA_RUNNER_WINDOWS=y
        - name: gen bin
          shell: cmd
          run: |
            mkdir bin
            cd bin
            echo jvav
            copy ..\jvav.exe .
            echo curl
            copy c:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin\libcurl-x64.dll .
            echo gcc
            copy c:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin\libgcc_s_seh-1.dll .
            echo std c++
            copy c:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin\libstdc^+^+-6.dll .
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            path: bin
            # platfrom-name-version-builder
            # todo: append _github_actions_hosted_runner to builder field where possible
            name: x86_64-pc-winnt-jvav-9git-azure_vm_winnt