name: x86_64 Ubuntu ? build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - run: "sudo apt install libcurl4-openssl-dev"
          name: "fucking soultion"
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"
        # fixme: fork bomb
        - name: make
          run: make -j
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            path: jvav
            # platfrom-name-version-builder
            # todo: append _github_actions_hosted_runner to builder field where possible
            name: x86_64-pc-linux-jvav-9git-azure_vm_ubuntu
  build-mingw-x86_64:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"
        # fixme: fork bomb
        # todo: you needed to dl curl-for-win?
        - name: make
          run: |
            curl -o curl-for-win.zip https://curl.haxx.se/windows/dl-7.70.0/curl-7.70.0-win64-mingw.zip
            7z e curl-for-win.zip -oC:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/x86_64-w64-mingw32
            7z e curl-for-win.zip -oC:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64
            make -j GHA_RUNNER_WINDOWS=y
        - name: Upload binary
          uses: actions/upload-artifact@v2
          with:
            path: jvav.exe
            # platfrom-name-version-builder
            # todo: append _github_actions_hosted_runner to builder field where possible
            name: x86_64-pc-winnt-jvav-9git-azure_vm_winnt