name: x86_64 Ubuntu ? build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: "sudo apt install libcurl4-openssl-dev"
      name: "fucking soultion"
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    # fixme: fork bomb
    - name: make
      run: make -j
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        path: jvav